-- ================================================================
-- Migration: Fix prototype_test_post_task_responses Foreign Key
-- Description: Corrects the task_id foreign key from tasks to prototype_test_tasks
-- Issue: Original migration referenced wrong table (tasks instead of prototype_test_tasks)
-- ================================================================

-- Drop the incorrect foreign key constraint
-- Note: The constraint name is auto-generated by Postgres as tablename_columnname_fkey
ALTER TABLE prototype_test_post_task_responses
  DROP CONSTRAINT IF EXISTS prototype_test_post_task_responses_task_id_fkey;

-- Add the correct foreign key constraint to prototype_test_tasks
ALTER TABLE prototype_test_post_task_responses
  ADD CONSTRAINT prototype_test_post_task_responses_task_id_fkey
  FOREIGN KEY (task_id) REFERENCES prototype_test_tasks(id) ON DELETE CASCADE;

-- Add comment explaining the fix
COMMENT ON COLUMN prototype_test_post_task_responses.task_id IS 'References prototype_test_tasks.id (fixed from incorrect tasks table reference)';
