-- Better Auth: OAuth 2.1 tables for the MCP server.
--
-- Why OAuth in addition to API keys: claude.ai on the web and the Claude Desktop
-- custom-connector UI accept OAuth only — neither has a field for a bearer
-- header or a custom header, so an API-key-only server cannot be installed as a
-- connector there at all. API keys stay the right credential for Claude Code,
-- Cursor, VS Code and anything headless.
--
-- Column naming is quoted camelCase, matching the live `session` / `account` /
-- `apikey` tables. See 20260730000000 for why the older migrations disagree.

CREATE TABLE IF NOT EXISTS public."oauthApplication" (
  id              TEXT PRIMARY KEY,
  -- DCR permits clients to omit a display name; the consent UI falls back to
  -- clientId in that case.
  name            TEXT,
  icon            TEXT,
  metadata        TEXT,
  -- Unique because oauthAccessToken and oauthConsent both reference it.
  "clientId"      TEXT NOT NULL UNIQUE,
  "clientSecret"  TEXT,
  -- Space- or comma-delimited list, written by the plugin.
  "redirectUrls"  TEXT NOT NULL,
  type            TEXT NOT NULL,
  disabled        BOOLEAN NOT NULL DEFAULT FALSE,
  -- Null for dynamically registered clients, which belong to no single user.
  "userId"        TEXT REFERENCES public."user"(id) ON DELETE CASCADE,
  "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public."oauthAccessToken" (
  id                      TEXT PRIMARY KEY,
  "accessToken"           TEXT NOT NULL,
  "refreshToken"          TEXT NOT NULL,
  "accessTokenExpiresAt"  TIMESTAMPTZ NOT NULL,
  "refreshTokenExpiresAt" TIMESTAMPTZ NOT NULL,
  "clientId"              TEXT NOT NULL REFERENCES public."oauthApplication"("clientId") ON DELETE CASCADE,
  "userId"                TEXT REFERENCES public."user"(id) ON DELETE CASCADE,
  scopes                  TEXT NOT NULL,
  "createdAt"             TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt"             TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public."oauthConsent" (
  id              TEXT PRIMARY KEY,
  "clientId"      TEXT NOT NULL REFERENCES public."oauthApplication"("clientId") ON DELETE CASCADE,
  "userId"        TEXT NOT NULL REFERENCES public."user"(id) ON DELETE CASCADE,
  scopes          TEXT NOT NULL,
  "consentGiven"  BOOLEAN NOT NULL DEFAULT FALSE,
  "createdAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  "updatedAt"     TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Reconcile tables that may have been generated by an earlier Better Auth
-- preview before this migration was recorded. These columns are required by
-- the installed plugin on every successful write.
ALTER TABLE public."oauthApplication"
  ALTER COLUMN "clientId" SET NOT NULL,
  ALTER COLUMN "redirectUrls" SET NOT NULL,
  ALTER COLUMN type SET NOT NULL;
ALTER TABLE public."oauthAccessToken"
  ALTER COLUMN "accessToken" SET NOT NULL,
  ALTER COLUMN "refreshToken" SET NOT NULL,
  ALTER COLUMN "accessTokenExpiresAt" SET NOT NULL,
  ALTER COLUMN "refreshTokenExpiresAt" SET NOT NULL,
  ALTER COLUMN "clientId" SET NOT NULL,
  ALTER COLUMN scopes SET NOT NULL;
ALTER TABLE public."oauthConsent"
  ALTER COLUMN "clientId" SET NOT NULL,
  ALTER COLUMN "userId" SET NOT NULL,
  ALTER COLUMN scopes SET NOT NULL;

-- Token lookup runs on every MCP request that authenticates via OAuth.
CREATE UNIQUE INDEX IF NOT EXISTS "idx_oauthAccessToken_accessToken"
  ON public."oauthAccessToken"("accessToken");
DROP INDEX IF EXISTS public."idx_oauthAccessToken_refreshToken";
CREATE UNIQUE INDEX "idx_oauthAccessToken_refreshToken"
  ON public."oauthAccessToken"("refreshToken") WHERE "refreshToken" IS NOT NULL;
CREATE INDEX IF NOT EXISTS "idx_oauthAccessToken_userId"
  ON public."oauthAccessToken"("userId");
-- Supports expiry sweeps.
CREATE INDEX IF NOT EXISTS "idx_oauthAccessToken_expiresAt"
  ON public."oauthAccessToken"("accessTokenExpiresAt");
-- The plugin records each approval as a new audit row, so these are lookup
-- indexes rather than a uniqueness constraint (re-consent must stay possible).
DROP INDEX IF EXISTS public."idx_oauthConsent_client_user";
CREATE INDEX IF NOT EXISTS "idx_oauthConsent_clientId"
  ON public."oauthConsent"("clientId");
CREATE INDEX IF NOT EXISTS "idx_oauthConsent_userId"
  ON public."oauthConsent"("userId");

ALTER TABLE public."oauthApplication" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."oauthAccessToken" ENABLE ROW LEVEL SECURITY;
ALTER TABLE public."oauthConsent" ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow service_role and postgres full access to oauthApplication"
  ON public."oauthApplication";
CREATE POLICY "Allow service_role and postgres full access to oauthApplication"
  ON public."oauthApplication" FOR ALL TO service_role, postgres USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow service_role and postgres full access to oauthAccessToken"
  ON public."oauthAccessToken";
CREATE POLICY "Allow service_role and postgres full access to oauthAccessToken"
  ON public."oauthAccessToken" FOR ALL TO service_role, postgres USING (true) WITH CHECK (true);
DROP POLICY IF EXISTS "Allow service_role and postgres full access to oauthConsent"
  ON public."oauthConsent";
CREATE POLICY "Allow service_role and postgres full access to oauthConsent"
  ON public."oauthConsent" FOR ALL TO service_role, postgres USING (true) WITH CHECK (true);

COMMENT ON TABLE public."oauthApplication" IS
  'Better Auth MCP: registered OAuth clients, including dynamically registered ones (RFC 7591). RLS enabled - service_role and postgres only.';
COMMENT ON TABLE public."oauthAccessToken" IS
  'Better Auth MCP: issued OAuth access and refresh tokens. RLS enabled - service_role and postgres only.';
COMMENT ON TABLE public."oauthConsent" IS
  'Better Auth MCP: per-user, per-client consent grants. RLS enabled - service_role and postgres only.';
