// Error codes follow the pattern: {DOMAIN}_{ACTION}_{REASON}
export const ErrorCodes = {
  AUTH_SESSION_EXPIRED: 'AUTH_SESSION_EXPIRED',
  AUTH_SESSION_INVALID: 'AUTH_SESSION_INVALID',
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_PERMISSION_DENIED: 'AUTH_PERMISSION_DENIED',

  VALIDATION_FAILED: 'VALIDATION_FAILED',
  VALIDATION_FIELD_REQUIRED: 'VALIDATION_FIELD_REQUIRED',
  VALIDATION_FIELD_INVALID: 'VALIDATION_FIELD_INVALID',
  VALIDATION_CONSTRAINT_VIOLATED: 'VALIDATION_CONSTRAINT_VIOLATED',

  RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
  RESOURCE_ALREADY_EXISTS: 'RESOURCE_ALREADY_EXISTS',
  RESOURCE_CONFLICT: 'RESOURCE_CONFLICT',
  RESOURCE_ARCHIVED: 'RESOURCE_ARCHIVED',

  STUDY_NOT_FOUND: 'STUDY_NOT_FOUND',
  STUDY_NOT_ACTIVE: 'STUDY_NOT_ACTIVE',
  STUDY_CLOSED: 'STUDY_CLOSED',
  STUDY_LIMIT_REACHED: 'STUDY_LIMIT_REACHED',
  STUDY_INVALID_TYPE: 'STUDY_INVALID_TYPE',

  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_ARCHIVED: 'PROJECT_ARCHIVED',

  PARTICIPANT_NOT_FOUND: 'PARTICIPANT_NOT_FOUND',
  PARTICIPANT_SESSION_INVALID: 'PARTICIPANT_SESSION_INVALID',
  PARTICIPANT_DUPLICATE_BLOCKED: 'PARTICIPANT_DUPLICATE_BLOCKED',
  PARTICIPANT_ALREADY_COMPLETED: 'PARTICIPANT_ALREADY_COMPLETED',

  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',

  SERVER_ERROR: 'SERVER_ERROR',
  SERVER_UNAVAILABLE: 'SERVER_UNAVAILABLE',
  DATABASE_ERROR: 'DATABASE_ERROR',
  EXTERNAL_SERVICE_ERROR: 'EXTERNAL_SERVICE_ERROR',

  NETWORK_ERROR: 'NETWORK_ERROR',
  REQUEST_TIMEOUT: 'REQUEST_TIMEOUT',
  REQUEST_ABORTED: 'REQUEST_ABORTED',
} as const

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes]

export function isErrorCode(code: string): code is ErrorCode {
  return Object.values(ErrorCodes).includes(code as ErrorCode)
}
