/**
 * Build script: bundles rrweb-snapshot's `snapshot` function into a minified IIFE string
 * that can be injected into client pages via the live-website snippet.
 *
 * Output: src/services/snippet/rrweb-snapshot-embed.ts
 * Usage: bun run build-rrweb-embed
 */
import { buildSync } from 'esbuild'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'

const ROOT = resolve(import.meta.dirname, '..')
const OUT_DIR = resolve(ROOT, 'src/services/snippet')
const OUT_FILE = resolve(OUT_DIR, 'rrweb-snapshot-embed.ts')

// Create a tiny entry that re-exports only `snapshot` from rrweb-snapshot
const entryCode = `
import { snapshot } from 'rrweb-snapshot';
window.__rrwebSnapshot = { snapshot };
`

// Write temporary entry file
const tmpEntry = resolve(ROOT, '.rrweb-embed-entry.ts')
writeFileSync(tmpEntry, entryCode)

try {
  const result = buildSync({
    entryPoints: [tmpEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    write: false,
  })

  const jsCode = result.outputFiles[0].text

  // Escape backticks and backslashes for template literal
  const escaped = jsCode
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')

  const tsContent = `// Auto-generated by scripts/build-rrweb-embed.ts — do not edit manually
export const RRWEB_SNAPSHOT_JS = \`${escaped.trim()}\`
`

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, tsContent)
} finally {
  // Clean up temp entry
  try {
    const { unlinkSync } = await import('fs')
    unlinkSync(tmpEntry)
  } catch {}
}
