/**
 * Build script: bundles @rrweb/record's `record` function into a minified IIFE string
 * that can be injected into client pages via the live-website snippet.
 *
 * Output: src/services/snippet/rrweb-record-embed.ts
 * Usage: bun run build-rrweb-record-embed
 */
import { buildSync } from 'esbuild'
import { writeFileSync, mkdirSync } from 'fs'
import { resolve, dirname } from 'path'

const ROOT = resolve(import.meta.dirname, '..')
const OUT_DIR = resolve(ROOT, 'src/services/snippet')
const OUT_FILE = resolve(OUT_DIR, 'rrweb-record-embed.ts')

// Create a tiny entry that re-exports only `record` from @rrweb/record
const entryCode = `
import { record } from '@rrweb/record';
window.__rrwebRecord = { record };
`

// Write temporary entry file
const tmpEntry = resolve(ROOT, '.rrweb-record-embed-entry.ts')
writeFileSync(tmpEntry, entryCode)

try {
  const result = buildSync({
    entryPoints: [tmpEntry],
    bundle: true,
    minify: true,
    format: 'iife',
    platform: 'browser',
    target: ['es2020'],
    write: false,
  })

  const jsCode = result.outputFiles[0].text

  // Escape backticks and backslashes for template literal
  const escaped = jsCode
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$/g, '\\$')

  const tsContent = `// Auto-generated by scripts/build-rrweb-record-embed.ts — do not edit manually
export const RRWEB_RECORD_JS = \`${escaped.trim()}\`
`

  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, tsContent)
} finally {
  // Clean up temp entry
  try {
    const { unlinkSync } = await import('fs')
    unlinkSync(tmpEntry)
  } catch {}
}
