/**
 * Generates src/backend/step-index.generated.ts — the explicit import list
 * that replaces motia's *.step.ts auto-discovery.
 *
 * Every src/steps/x/y.step.ts becomes an entry { id: 'steps::x/y', mod }, and
 * every *.stream.ts a stream module entry. Deterministic (sorted) output so
 * the file only changes when the step set changes.
 *
 * Usage:
 *   bun scripts/generate-step-index.ts           # one-shot
 *   bun scripts/generate-step-index.ts --watch   # regenerate on add/remove
 *
 * In watch mode this pairs with `bun --watch src/backend/main.ts`: a new step
 * file rewrites the index → bun sees the import graph change → restarts →
 * the new step registers.
 */

import { watch } from 'node:fs'
import { mkdirSync, readFileSync, writeFileSync, existsSync } from 'node:fs'
import path from 'node:path'

const APP_DIR = path.resolve(import.meta.dir, '..')
const STEPS_DIR = path.join(APP_DIR, 'src', 'steps')
const OUT_FILE = path.join(APP_DIR, 'src', 'backend', 'step-index.generated.ts')

function collect(): { steps: string[]; streams: string[] } {
  const stepGlob = new Bun.Glob('**/*.step.ts')
  const streamGlob = new Bun.Glob('**/*.stream.ts')
  const exclude = (p: string) => p.includes('__tests__') || p.endsWith('.test.ts')

  const steps = [...stepGlob.scanSync({ cwd: STEPS_DIR })].filter((p) => !exclude(p)).sort()
  const streams = [...streamGlob.scanSync({ cwd: STEPS_DIR })].filter((p) => !exclude(p)).sort()
  return { steps, streams }
}

function render(steps: string[], streams: string[]): string {
  const lines: string[] = [
    '/* eslint-disable */',
    '// AUTO-GENERATED by scripts/generate-step-index.ts — do not edit.',
    '// Regenerate: bun run generate:steps',
    "import type { StepModule } from '../lib/iii/register-step'",
    "import type { StreamModule } from '../lib/iii/register-streams'",
    '',
  ]

  steps.forEach((p, i) => {
    lines.push(`import * as step${i} from '../steps/${p.replace(/\.ts$/, '')}'`)
  })
  streams.forEach((p, i) => {
    lines.push(`import * as stream${i} from '../steps/${p.replace(/\.ts$/, '')}'`)
  })

  lines.push('', 'export const steps: ReadonlyArray<{ id: string; mod: StepModule }> = [')
  steps.forEach((p, i) => {
    const id = `steps::${p.replace(/\.step\.ts$/, '')}`
    lines.push(`  { id: ${JSON.stringify(id)}, mod: step${i} as unknown as StepModule },`)
  })
  lines.push(']', '', 'export const streams: ReadonlyArray<StreamModule> = [')
  streams.forEach((_p, i) => {
    lines.push(`  stream${i} as unknown as StreamModule,`)
  })
  lines.push(']', '')
  return lines.join('\n')
}

function generate(): boolean {
  const { steps, streams } = collect()
  const content = render(steps, streams)
  mkdirSync(path.dirname(OUT_FILE), { recursive: true })
  const previous = existsSync(OUT_FILE) ? readFileSync(OUT_FILE, 'utf8') : null
  if (previous === content) return false
  writeFileSync(OUT_FILE, content)
  console.log(`[generate-step-index] ${steps.length} steps, ${streams.length} streams → ${path.relative(APP_DIR, OUT_FILE)}`)
  return true
}

generate()

if (process.argv.includes('--watch')) {
  let timer: ReturnType<typeof setTimeout> | null = null
  watch(STEPS_DIR, { recursive: true }, () => {
    // Debounce bursts (editor saves, git checkouts); content-hash guard in
    // generate() means unchanged sets never touch the file.
    if (timer) clearTimeout(timer)
    timer = setTimeout(generate, 200)
  })
  console.log('[generate-step-index] watching src/steps for step add/remove')
}
